name = "aviation-tracker"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "aviation_db"
database_id = "YOUR_DB_ID"

[site]
bucket = "./dist" 

[vars]
JWT_SECRET = "sk_5c4r5_53cr3t_k3y_2024"