name = "skycars-worker"
main = "functions/worker.js"
compatibility_date = "2024-01-01"

[triggers]
crons = []

[env.production]
routes = [
  { pattern = "api.skycars.app/*", zone_id = "your-zone-id" }
]

# Add your environment variables here
[vars]
ENVIRONMENT = "production"

# Configure caching behavior
[site]
bucket = "./public"
entry-point = "functions/worker.js"

[[kv_namespaces]]
binding = "SKYCARS_CACHE"
id = "your-kv-namespace-id"
